language: python
branches:
  only:
    - master

python:
  - "2.6"
  - "2.7"

install:
  - "sudo apt-get install build-essential pkg-config ruby rake libseccomp-dev -y"
  - "cd lib/lrun/"
  - "LRUN_GROUP=travis make install"

script:
  - "python test.py"
